# enable mouse
set -g mouse on

# enable vim motions in tmux copy mode
setw -g mode-keys vi

# rebind prefix to C-a
unbind-key C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# rebind pane navigation to mimic vim motions
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# rebind begin/end selection to mimic yanking in vim visual mode
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel

# rebind splits and new windows to use the cwd
bind '"' split-window -v -c "#{pane_current_path}"
bind %   split-window -h -c "#{pane_current_path}"
bind c   new-window      -c "#{pane_current_path}"

# address vim mode switching delay (http://superuser.com/a/252717/65504)
set -s escape-time 0
